version: '3'
services:
  ssh:
    hostname: kali-docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volumes/root:/root/host
    environment:
      - VNC_PASSWORD=Foobar@123
    ports:
      # You can use any port, but 443 is normally allowed through corp firewalls.
      - "443:22"
      # CCC
      - "6666-6676:6666-6676"
      # mosh  
      - "60001-60011:60001-60011/udp"
      # Free utility port for metasploit etc.
      - "666-676:666-676"
      # Uncomment to expose VNC (bad idea)
      #- "80:80"
      #- "5900:5900"


